### ISSUE TITLE
Visemes not Detected

### ISSUE THREAD

**Issue by matt-marek** [malaybaku/VMagicMirror#11]
Lip Sync (A E I O U) isn't detected on some VRM models. 

I have tested a model with other programs, such as VDRAW and VRMViewer, which shows the mouth movement as working. However, I have models that lip sync works with VMagicMirror, so I cannot determine what might be the cause.

 I can provide the VRM file if it is useful for testing the issue.

**Comment by malaybaku** [comment]
Thank you for the report, I confirmed that it was a bug in VMagicMirror. In the next version this issue will be fixed (I will release it in this weekend).

This issue happens when the VRM does not have some of finger bones. During this issue, the finger motion feature also becomes unavailable.

The fix code is in #12 .
