### ISSUE TITLE
Windows 10 - Avatar Window out of Screen

### ISSUE THREAD

**Issue by M4CC** [malaybaku/VMagicMirror#280]
Hello,

First of all thank you for VMagicMirror, it's an amazing software.

I'm having an issue with Windows 10 where the image that displays the avatar is out of the screen's usable area. I can see the window when I alt+tab through them and the avatar displays within OBS but when I click the window on the task bar it doesn't pop into view.

Are you aware of this issue? How can I help you troubleshoot it?

Thank you!

**Comment by malaybaku** [comment]
Hello, 

Please try `OpenSettingWindow` > `Window` tab > `Reset Character Position` so that the character window will come just right to the control panel.

![image](https://user-images.githubusercontent.com/13213534/82973456-63a78580-a012-11ea-89a4-97be025b95c5.png)

**NOTE:** There is a known issue that, this recover way is unavailable during automatic VRoid Hub avatar load process. In this case please remove `(.exe folder)/ConfigApp/_autosave` file to reset the setting.

**Comment by malaybaku** [comment]
Close because the question is already in FAQ document.

https://malaybaku.github.io/VMagicMirror/en/questions 
"After loading VRM character window seems disappear"
