### ISSUE TITLE
Is free version still working?

### ISSUE THREAD

**Issue by picolojunior** [malaybaku/VMagicMirror#293]
Seem like not work for me anymore or I need to buy license one?
It did not load the vrm file character the green one.
I try disable all virus protection still no work sad.

**Comment by malaybaku** [comment]
Hi,

VMagicMirror has NO paid version. BOOTH paid option results no difference in the software.

Please check following possible causes.

- OS Version: Only Windows 10 supported (32bit OS also might lead problem) 
- Model specific issue: especially please try to load [Alicia Solid](https://3d.nicovideo.jp/works/td32797) and VRoid Studio default model, to check the issue is about model data or the software itself.

**Comment by picolojunior** [comment]
yeah just recheck again the model show when alt cap lock but when not alt cap it not shown.

**Comment by picolojunior** [comment]
Hi thank for the answer I think it was bug the way to fix is right click on Vmagic mirror that already open on task bar and left click it to re open unity again and that would fix the missing model.
