### ISSUE TITLE
ゲーム内のキーストロークを追跡するアバター

### ISSUE THREAD

**Issue by niveumi** [malaybaku/VMagicMirror#345]
こんにちは、プログラムありがとうございます。ゲームをプレイしているときにもアバターがキーストロークをモニターできるようにしたいのですが、現在のところ、ゲームにタブで参加している間だけマウスの動きをトラッキングしてくれます。この動きを追跡するように切り替えることができるAPIはありますか？

**Comment by malaybaku** [comment]
フィードバックありがとうございます。類似のフィードバックを英語のインプットでも頂いていることを踏まえて、日英併記で回答します。
Thank you for feedaback. I will reply for this issue in JP/EN, as I have received similar feedback both in Japanese and English.

> ゲームをプレイしているときにもアバターがキーストロークをモニターできるようにしたい
> (Want to track key stroke even when playing specific games)

こちらについては、現状(v1.2.0)だと切り替えることができません。
Sorry, current version (v1.2.0) does not support it.

一部のゲームでこの問題が起きることを把握しており、技術的にはこのissueは #327 に相当します。
本フィードバックを受けまして、次のリリースバージョンv1.3.0時点で修正できるよう、優先度を上げて対応します。
I know some game applications have same issue, and this issue points same technical cause as #327.
I will put higher priority to fix #327 according to your feedback, so that the fix will be released in next version (v1.3.0).

> ゲームにタブで参加している間だけマウスの動きをトラッキングしてくれます

マウスについては、もしゲーム内でトラッキングが有効でない場合、設定ウィンドウの以下のチェックをオンにすることを試してください。
When you have mouse tracking trouble during playing game (especially FPS), please try turning on the following check box. 

- 設定ウィンドウ > `モーション`タブ > `腕・ひじ` > `右手のマウス動作をFPS対策モードにする)`
- Setting Window > `Motion` tab > `Arm` > `Enable mouse motion to FPS assumed mode`

**Comment by niveumi** [comment]
迅速な対応と感想を聞いていただき、ありがとうございました 更新を楽しみにしています。
