### ISSUE TITLE
Support for custom motions that can be used with the word-to-motion feature?

### ISSUE THREAD

**Issue by RaVenInTheDark** [malaybaku/VMagicMirror#408]
Could it be possible to add support for custom motions, I'm not sure what file type would be required, that can be used with the word-to-motion feature? The built in two don't provide much of a variety and adding support for custom ones would make for a huge improvement.

**Comment by malaybaku** [comment]
@RaVenInTheDark 
Thank you for feedback.

I know of some choices for custom motion support, like:

- BVH
- Unity Asset Bundle
- Unity .anim file (*this will be easy to use when using, but might difficult...)

I tried custom motion support once before and gave up, but the issue was rather usability than technically severity.
Based on this, I add this issue to Milestone v1.6.0, the release scheduled in Nov.

**Comment by RaVenInTheDark** [comment]
@malaybaku 
It's great to hear you have support planned soon. I'm not too good with Unity but if you need help, I'm happy to try what I can.

**Comment by malaybaku** [comment]
close, as supported in v1.6.0.

- https://malaybaku.github.io/VMagicMirror/tips/use_custom_motion
- https://malaybaku.github.io/VMagicMirror/en/tips/use_custom_motion
