### ISSUE TITLE
Features Ideas

### ISSUE THREAD

**Issue by DemonRem** [malaybaku/VMagicMirror#412]
1st , maybe adding body tracking with the camera like luppet will be great thing to do
2nd luppet have a nice feature that i think vmagicmirror can have too since lips tracking already function already exist
is the adjust the volume sensitivity
3rd eyes movment and blink as the user doing not working or not even exist its possible to add such function?

**Comment by malaybaku** [comment]
@DemonRem 
Thank you for the ideas,

> 1st , maybe adding body tracking with the camera like luppet will be great thing to do

I will consider, but not at the highest priority, because of the technical challenge on performance and CPU load trade-off.

> 2nd luppet have a nice feature that i think vmagicmirror can have too since lips tracking already function already exist
is the adjust the volume sensitivity

I will add it on next release (v1.5.0) as it feels very straight-forward and has little demerit.

> 3rd eyes movment and blink as the user doing not working or not even exist its possible to add such function?

Will consider but might be difficult. I will introduce it in next two versions (v1.5.0 or v1.6.0). I also think eye jitter motion can be bigger than current, so this update will include those parameter adjust.

**Comment by DemonRem** [comment]
hey @malaybaku 

there is another thing i forget to ask you
is there a plan to support motion leap device in feature?

**Comment by malaybaku** [comment]
@DemonRem 
Thanks for proposal, but I do not plan it because Luppet intensively supports Leap Motion and is doing very well, so no motivation for creating free (but low-quality) version.
Also I have no plan to support other tracking-specialized gadgets, because of cost performance policy.

**Comment by DemonRem** [comment]
ok thanks for the answer.
