### ISSUE TITLE
Expression Idea 

### ISSUE THREAD

**Issue by DemonRem** [malaybaku/VMagicMirror#428]
hey @malaybaku 
would you add to the program function that , can recognized face expression
by the webcam?

**Comment by malaybaku** [comment]
@DemonRem 
Thanks for the idea, but now is not the timing because :

- This requires higher webcam resolution so #415 should be solved first
- Current VRM BlendShape standard is not suited for those exression unless I could achieve very high precision. VRM 1.0 will be more comfortable in this point.

Based on those point I put label "VRM 1.0" to this issue.

**Comment by malaybaku** [comment]
close as staled issue
