### ISSUE TITLE
Feature request: Flexible expression hotkey assigment

### ISSUE THREAD

**Issue by EatThePath** [malaybaku/VMagicMirror#514]
It would be useful if the "word to motion" actions could be build to keys like in a traditional game. By using keyboard(word) with single letters you can get some of the functions that would allow, but you can't bind to function keys, modifier key combinations, or similar things.

**Comment by malaybaku** [comment]
@EatThePath 
Thanks for feedback, and sorry for late reply.

I do not plan to support hotkey based expression, because it might lead very unexpected behavior when use it with another software.

If you need additional method to support triggering facial expression by simple way, please consider to introduce X-Input compliant game controller, or MIDI controller.

Example process:

- Start VMagicMirror 
- Setup hotkey expression (e.g. `Ctrl+Shift+D`) in VMagicMirror 
- Focus to another tool software
- Press Ctrl+Shift+D

In this case `Ctrl+Shift+D` is also recognized in another active software and it might be harmful on another software (for example, delete something in progress). 
And what the worse is , it is possible that user even do not know that shortcut is supported in the software.
This type of problem is mainly caused by hotkey, so I do not support it.
