### ISSUE TITLE
LipSync does not work in specific environment.

### ISSUE THREAD

**Issue by malaybaku** [malaybaku/VMagicMirror#516]
User report.

- Might be because very high frequency mic up to 192KHz), but in report several mics tested and problem reproduced.
- In that environment VMagicMirror and Luppet fail to run lipsync, while VSeeFace works.

**Comment by MicaVsr** [comment]
Hi malaybaku, 
I was looking for some help because I'm having an issue with LipSync and I found that you are planning to fix something related.

Currently I'm using VMagicMirror 1.6.2 (I tested with the new version, 1.7.0, but still not working ) and the issue is in the Microphone dropdown, It did't show my microphones. 
Here I attached an image to show you:
![image](https://user-images.githubusercontent.com/42984098/118436192-c1ffc500-b6b6-11eb-957d-497d82ed588d.png)

And also here is the "Manage Sound Devices" section in Windows Settings, were you can see that I have 2 of them:
![image](https://user-images.githubusercontent.com/42984098/118436777-c9739e00-b6b7-11eb-9c4d-72f3dfdf7149.png)
_(sorry, It's in spanish but there it says "Input Devices" and then the list of microphones)_

The one I want to use is the second one that uses the driver _Realtek High Definition Audio_ and has an audio jack of 3,5 mm.

Today I was testing some gamer headphones with microphone, conected by USB and for some reason the microphones dropdown were showing all of my microphones, but when I discconected them and open VMagicMirror again, all of them disappear.

<h2>Resume:</h2>

- **OS**: Windows 10 PRO (version 10.0.18363.1556)
- **VMagicMirror** 1.6.2 and 1.7.0
- **Microphone**: Boya BY-M1 [http://www.boya-mic.com/lavaliermicrophones/BY-M1.html](url)
- **Drivers**: Realtek High Definition Audio

<h3>Issue:</h3>
Microphones aren't showed in the dropdown in LipSync configuration.
When a headset is connected by USB, all microphones are showed. When you disconnect them, all disappear.<br><br>

I hope all this information helps. I didnt's spect a response but if you need more information, just let me know.

**Comment by malaybaku** [comment]
#586 merge will improve the situation, but some issue might remains.

**Comment by malaybaku** [comment]
Just memo:

There exists user report which indicates #640 leads microphone input trouble in specific environment.

I am not clear whether NAudio is more unstable than Unity standard microphone, or just they have different weak points.

**Comment by malaybaku** [comment]
Set milestone to v2.0.0, because next release of v1.9.3 (it will be v2.0.0) should have detailed log feature for microphone input trouble

**Comment by malaybaku** [comment]
https://github.com/malaybaku/VMagicMirror/issues/516#issuecomment-997159509

This was not correct, which means when NAudio fails, Unity's standard process also fails (by older version of VMagicMirror).

Also the user reported that Luppet works correctly in the same environment.

**Comment by malaybaku** [comment]
Based on new user report with v2.0.0, this issue may can happen when anti-virus (like Kaspersky) try to disturb microphone input capture.

Based on above, workaround is simply to write about it on FAQ page...

**Comment by malaybaku** [comment]
I close the issue as resolved and make ref to #664 , which should have had an impact on microphone detection stability
