### ISSUE TITLE
Body Extrenal Tracking

### ISSUE THREAD

**Issue by DemonRem** [malaybaku/VMagicMirror#519]
hey @malaybaku 
listen i can use my iphone to track my face only but i want to track my hands too
so i cant active the camera during that , is there any thing i can do?

**Comment by DemonRem** [comment]
also when on iphone tracker mode the model not blink

**Comment by malaybaku** [comment]
Hi @DemonRem ,

> listen i can use my iphone to track my face only but i want to track my hands too
> so i cant active the camera during that , is there any thing i can do?

Sorry but I do not plan to support this use case, because it promotes complicated device arrangement.
If you think this feature important, please consider to use Luppet or VSeeFace.

> when on iphone tracker mode the model not blink

It seems model setup issue, especially if you are using Perfect Sync feature. Please see this page to check blendshape setup.

https://malaybaku.github.io/VMagicMirror/en/tips/perfect_sync

It is also possible that iFacialMocap's upper face tracking is disabled. Please see this troubleshoot Q4.

https://malaybaku.github.io/VMagicMirror/en/docs/external_tracker_ifacialmocap#troubleshoot

**Comment by DemonRem** [comment]
i check it soon as i finish eat , thank for the replay @malaybaku

**Comment by DemonRem** [comment]
another thing is i cant speak from my microphone the tool recognize it but once i check the vol on the tool its stay on grey 
the microphone is "Skiller SGH2"

**Comment by malaybaku** [comment]
@DemonRem 

> another thing is i cant speak from my microphone

Do you use it with iOS device?

In this case, check `External Tracker` > `Apply LipSync using External Tracker Data` is turned off. 

If `Apply LipSync using External Tracker Data` is on, the mouth blendshape moves according to iOS device recognition result and microphone based lipsync does not start.

**Comment by DemonRem** [comment]
yes i use ios device

**Comment by malaybaku** [comment]
@DemonRem 
I wrote to **TURN OFF** `Apply LipSync using External Tracker Data ` checkbox to enable microphone, in previous comment.

Did it help, or microphone is still not recognized in volume indication?

**Comment by DemonRem** [comment]
no

**Comment by malaybaku** [comment]
@DemonRem 
Sorry for very late response.

Now I am receiving at least 3 reports about microphone connection issue which seems to depends on environment, including #516 . I am not still sure what is the cause.

In my understanding your microphone is not recognized even when iOS face tracking feature is totally disabled. Is it correct?

**Comment by malaybaku** [comment]
close, because:

- discussion has been stopped 
- microphone issue seems to be a duplication of #516
