### ISSUE TITLE
Option to make bloom only apply based on emission maps

### ISSUE THREAD

**Issue by Boundarybreaker** [malaybaku/VMagicMirror#526]
I recently added emission maps to my VRoid model so that I could have a glowing effect. I wanted to add a bloom effect as well, but I found that VMagicMirror's bloom only applies to the entire model.

With the bloom intensity set to 500 and the bloom threshold set to 100, the model looks like this:
![](https://user-images.githubusercontent.com/6722691/112748042-19629e00-8f6e-11eb-85cf-6e434e2d8c98.png)

With the bloom intensity set to 500 and the bloom threshold set to 80, the model looks like this:
![](https://user-images.githubusercontent.com/6722691/112748067-3e571100-8f6e-11eb-81fe-0bad22d7df5b.png)

In VSeeFace with intensity and threshold set to similar levels as the second picture, the model looks like this:
![](https://user-images.githubusercontent.com/6722691/112748082-5dee3980-8f6e-11eb-9ba3-12305c465315.png)

I would like an option that lets the bloom in VMagicMirror only apply based on the set emission maps of the model, instead of the entire model. VMagicMirror does too many things I use that VSeeFace doesn't (keyboard and gamepad input viewing, better external tracking support, fewer mesh errors) for this feature to be worth switching programs, so I hope this can be added to VMagicMirror.

**Comment by malaybaku** [comment]
Hi @Boundarybreaker ,

Sorry for late response.

I tried to improve the situation but could not.

Please try to adjust your model's emission material (especially HDR value), and gain the bloom threshold to fix the problem.

Your request is reasonable from the point of usability, 

> an option that lets the bloom in VMagicMirror only apply based on the set emission maps

However I cannot realize it because post-process bloom does not allow such operation.

Post process based on only the rendered pixels so the process cannot classify the color comes from emission map or not.

I think the appearance difference between VSeeFace and VMagicMirror comes other rendering settings like colorspace.

**Comment by Boundarybreaker** [comment]
Ah right, postprocessing limitations. Thank you for trying!
