### ISSUE TITLE
Virtual Camera Output missing in version 1.6

### ISSUE THREAD

**Issue by hikaruAi** [malaybaku/VMagicMirror#541]
In the latest version there is not Virtaul webcam output. Asking to know if it is a bug or the feature is desprecated
Thanks

![unknown (1)](https://user-images.githubusercontent.com/6921914/115939778-6e55df00-a45c-11eb-9936-8323c1d80572.png)

**Comment by malaybaku** [comment]
HI @hikaruAi , 

I have removed this feature in v1.6.0.

The reason is that, OBS Studio has virtual camera feature since v26.0 by default, and it is enough easy to use. 

- Changelog: https://malaybaku.github.io/VMagicMirror/en/changelog
- Tips: https://malaybaku.github.io/VMagicMirror/en/tips/virtual_camera

**Comment by hikaruAi** [comment]
Thanks

**Comment by DanskieTV** [comment]
The one on obs doesn't work with discord so I kinda need this added back or the option to back to older versions.

**Comment by PoptartGhost** [comment]
I have the same problem as DanskieTV please add this feature back or allow us to roll back.

**Comment by kanashimiofc** [comment]
Please i beg you bring it back
