### ISSUE TITLE
Expression transition

### ISSUE THREAD

**Issue by rcsaquino** [malaybaku/VMagicMirror#553]
Hi, malaybaku! 

Would it be possible to add a setting that allows us to smoothen the transition between expressions? For example, when the expression is angry, and you want to transition to joy, the avatar should slowly smile and not abruptly. That way, it's more natural and realistic.

Thanks!

**Comment by malaybaku** [comment]
Hi @rcsaquino , thanks for feedback.

I do not plan the feature, mainly because of the limitation of VRM standard.

VRM does not ensure that BlendShape keeps its appearance during transition, so it may lead bad look especially for her/his eye mesh. 

There is also some workaround like transition with inserted neutral clip (e.g. "angry > neutral > joy"), but I think it is not what you want.

**Comment by rcsaquino** [comment]
Hi! @malaybaku!

I see. Too bad if that's the case. I just thought it would be possible since other programs such as VSeeFace allows has such feature.

I also noticed there are no "look down/up" animations when tracking the face. Maybe it's just subtle?

Thanks for the response!

**Comment by malaybaku** [comment]
Thanks for response, 

> there are no "head up/down" animations when tracking the face.

I think I should add some built-in head motion for this purpose. I created a new issue #561 .

**Comment by malaybaku** [comment]
Closing this issue, since the discussion is completed
