### ISSUE TITLE
How to fit the general model except vrm

### ISSUE THREAD

**Issue by hahaCrazy** [malaybaku/VMagicMirror#577]
Thank you very much to the author, I can use the vrm model to control keyboard typing, because the rotation specifications of the vrm bones are basically uniform, but after the models made by our art are imported into unity, the bones of different models are rotated differently, which leads me It is impossible to use the calculation method like vrm bone to realize model typing, so how can I do it, please help!

**Comment by malaybaku** [comment]
Hi @hahaCrazy ,

First of all, I am very glad to see your challenge.

I answer to the question with general solution, but I don't want to get into further explanation.
This is because the question is fundamentally not related to VMagicMirror itself.
I close this issue after the response.

--- 

One of the straight forward approach is to create virtual bone as an initilization when loading non-VRM model.
The model must be in T-pose when generating virtual bone.

Virtual bone is the concept to control each (non-VRM) model's bone as if the bones have same coordinate system as VRM.
This concept is equivalent to cache global rotation of each bone when the model is in T-pose.

With those cached bone information, you can apply VRM-styled rotation to each bone using target rotation and cached rotation.

It is VERY IMPORTANT that I do not remember exact code, though I have some experiences to apply this approach in Unity and I believe it a valid way.

The code will be something like following, but please think you must fix it to work correctly.

```
Quaternion targetRotation = ...;
bone.rotation = bone_initRot * targetRotation * Quaternion.Inverse(bone_initRot);
```

The approach mainly focuses on forward kinematics, but in my understanding, you also need to apply them to IK with rotation weight.

When you try this approach, I strongly recommend to create and test in minimal scene first, as VMagicMirror main scene has too much bone adjust processes.

---

I hope it will be your help.

**Comment by hahaCrazy** [comment]
In fact, I have already referred to the demo of VMagicMirror to realize the keyboard interaction function, and the code is quite concise (I use Dotween to do smooth assignment), without using zenject, you can help me see how to optimize my code . Because I still don't understand the concept of virtual bones you mentioned, and don't know how to do it, can you take a look at my code?







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "malaybaku/VMagicMirror"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月27日(星期四) 中午12:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [malaybaku/VMagicMirror] How to fit the general model except vrm (#577)





 
Hi @hahaCrazy ,
 
First of all, I am very glad to see your challenge.
 
I answer to the question with general solution, but I don't want to get into further explanation.
 This is because the question is fundamentally not related to VMagicMirror itself.
 I close this issue after the response.
 
 
One of the straight forward approach is to create virtual bone as an initilization when loading non-VRM model.
 The model must be in T-pose when generating virtual bone.
 
Virtual bone is the concept to control each (non-VRM) model's bone as if the bones have same coordinate system as VRM.
 This concept is equivalent to cache global rotation of each bone when the model is in T-pose.
 
With those cached bone information, you can apply VRM-styled rotation to each bone using target rotation and cached rotation.
 
It is VERY IMPORTANT that I do not remember exact code, though I have some experiences to apply this approach in Unity and I believe it a valid way.
 
The code will be something like following, but please think you must fix it to work correctly.
 Quaternion targetRotation = ...; bone.rotation = bone_initRot * targetRotation * Quaternion.Inverse(bone_initRot);  
The approach mainly focuses on forward kinematics, but in my understanding, you also need to apply them to IK with rotation weight.
 
When you try this approach, I strongly recommend to create and test in minimal scene first, as VMagicMirror main scene has too much bone adjust processes.
 
 
I hope it will be your help.

**Comment by malaybaku** [comment]
@hahaCrazy 
Please see my previous response.
I do not explain any further detail. 

I think the matter is that, you will need to learn some mathematical background about general 3D rotation control by Quaternion. Such knowledge is necessary to grasp the concept of virtual bone. 
I correct previous reply. The concept is straight forward, only if you have rich 3D mathematics background. Please take time to understand the concept.

And, as I have replied, such topic is beyond VMagicMirror project, because VRM does not require to solve those general rotation problem. 

Again, your question is not related to VMagicMirror directly.
That is why I do not answer this question in detail.

**Comment by hahaCrazy** [comment]
thank you for your reply，I will try my best to realize it



---Original---
From: "Baku ***@***.***&gt;
Date: Thu, May 27, 2021 18:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [malaybaku/VMagicMirror] How to fit the general model except vrm (#577)




 
@hahaCrazy
 Please see my previous response.
 I do not explain any further detail.
 
I think the matter is that, you will need to learn some mathematical background about general 3D rotation control by Quaternion. Such knowledge is necessary to grasp the concept of virtual bone.
 I correct previous reply. The concept is straight forward, only if you have rich 3D mathematics background. Please take time to understand the concept.
 
And, as I have replied, such topic is beyond VMagicMirror project, because VRM does not require to solve those general rotation problem.
 
Again, your question is not related to VMagicMirror directly.
 That is why I do not answer this question in detail.
