### ISSUE TITLE
[Feature]ZOrder Option

### ISSUE THREAD

**Issue by LievreAI** [malaybaku/VMagicMirror#578]
will be nice if you can add option to do zoption mean
if i play fullscreen games zorder 1 will bring VMagicMirror into the front in the fullscreen game
zorder 0 will bring it to the back of the fullscreen game

**Comment by malaybaku** [comment]
@LievreAI 
Thanks for the contact, but I do not plan to support for the request.
When you find a game that hide VMagicMirror, then please consider to disable game's full screen mode.

Please see detail as following.

### 1. What VMagicMirror already does

VMagicMirror already has the feature about ZOrder. There is a checkbox `Always Foreground` toggle in setting window `Window` tab. This feature is enabled by default, and is active during character window background is transparent.

### 2. What VMagicmirror can / cannot now

I have checked several game applications and found that there are games the ZOrder feature work, and does not work.

- ZOrder works correctly with most of Unity Engine based games.
- Other games prevent ZOrder feature, so that VMagicMirror window does not go foreground.

### 3. Why I cannot support further 

Windows API seems not have any answers for your request. Please see this for the detail.

https://devblogs.microsoft.com/oldnewthing/20110310-00/?p=11253

**Comment by LievreAI** [comment]
i get my answer thanks :)
