### ISSUE TITLE
Blink/Auto Blink not working with Material only blend shape

### ISSUE THREAD

**Issue by Darksteelhorse** [malaybaku/VMagicMirror#624]
Issue:  The avatar I exported only uses material UV offsets to change its expressions for both the mouth and face. The mouth works as one would expect, but the eyes do not. The biggest issue is that when the blink activates, the character's face goes completely blank. [Video of issue (gfycat)](https://gfycat.com/cavernousidealisticiberianmidwifetoad)

Hardware:
i7-7700k
16gb ram
EVGA 1070 SC
Logitech C9930

**Comment by malaybaku** [comment]
Hi @Darksteelhorse ,

I reply two points.

1. VMagicMirror is not good at material based blendshapes.

Sorry but it is by design and difficult to fix, so you might feel the eye motion is not so good.

2. Blendshape clip settings seem incorrect.

Please check `BLINK_L` and `BLINK_R` settings.

VRM specification expects `BLINK_L` to be the clip to close only left eye, and `BLINK_R` is only for right eye.

In the video both clips seem to be designed to close both eyes, which may lead odd appearance.

If it is difficult to separate those clips, then please consider a workaround that:

- Keep BLINK_L as is.
- Fix BLINK_R to be a clip which does nothing.

**Comment by Darksteelhorse** [comment]
That is fair, when I made the `BLINK_L` and `BLINK_R` blendshape clips, it was merely for testing to see if anything would change. I appreciate the response.
