### ISSUE TITLE
Feature Request: Adjustments to Controller Input Animation

### ISSUE THREAD

**Issue by bitbot-marina** [malaybaku/VMagicMirror#760]
The controller input is a really handy feature, though the "leaning" with stick input isn't always appropriate for some games.

It would nice to be able to do some of the following:
- Enable/disable character "leaning" based on input
- Assign input for lean (most controllers support Right Stick/Left Stick)
- Adjust sensitivity for lean. For example, lean only occurs at once the stick is fully pressed.
- Replace controller model with user model, such as FBX

**Comment by malaybaku** [comment]
@bitbot-marina 

Thanks for feedback,

> - Enable/disable character "leaning" based on input
> - Assign input for lean (most controllers support Right Stick/Left Stick

These are supported feature, detail is in: https://malaybaku.github.io/VMagicMirror/en/docs/devices

> - Replace controller model with user model, such as FBX

I think texture replacement feature is an enough good alternative for this request: https://malaybaku.github.io/VMagicMirror/en/tips/change_textures

> - Adjust sensitivity for lean

I think this is reasonable request, but I do not plan it since it seems too detailed setting.
