### ISSUE TITLE
not a issue but a question-ish

### ISSUE THREAD

**Issue by FoxFireVR** [malaybaku/VMagicMirror#771]
so i had to use my daughters pc to stream for a bit and i was too rushed/lazy to install VMM , so i used a webbased vrm thing, and using cam it offered hand and (experimental) full body tracking, and also limited face tracking, like blink detection, and if you opened your mouth it detected that also, i was wondering if that would be a option for future updates in VMM, and also i was wondering, if you could also be able to use trackers and VR stuff so while playing VR games i could have my VRM on also ?? or is that more work than is worth? just wondering, i love VMM by the way best money spent by far!!!

**Comment by malaybaku** [comment]
Thanks for contact,

I think these requests reasonable, but I am not so motivated for them.　This is because there exists some alternative solutions. For example, 

- VSeeFace works well for webcam based face tracking.
- Virtual Motion Capture is a powerful app for VR tracker related motion capture system.

I recommend those apps when they are more suited for the purpose.

Especially about the first case, VMM development policy prefers less PC load than higher tracking performance. It is also the reason why I support iOS app based tracking, instead of improving webcam tracking precision.
