### ISSUE TITLE
Ultraleap for hand 

### ISSUE THREAD

**Issue by Sheiylanie** [malaybaku/VMagicMirror#806]
Hi, I'm contacting you because I really like your application, I'd like to use Ultraleap for hand movements and I'd like to know if it's possible to add it.

you have a unity package here : https://developer.leapmotion.com/unity

**Comment by malaybaku** [comment]
@Sheiylanie 
Thanks for proposal, but I do not have plan to support LeapMotion.

It is by design that VMagicMirror does not use devices which is specialized to body, head, or hand tracking.
Supporting iFacialMocap is because it is smartphone based solution.

Please consider to introduce other app for example Luppet, VSeeFace, etc.
