### ISSUE TITLE
VMagicMirror won't stay on top of applications

### ISSUE THREAD

**Issue by phourniner** [malaybaku/VMagicMirror#905]
Hi, I am trying to use VMagicMirror in my streaming, but it won't stay "on top" of applications, like games.

I am using OBS and everything is set up correctly as far as I know. Using Game Capture with VMagicMirror, everything works fine except the capture window goes away when I click into the game.

Any suggestions? I honestly could be missing something important that I forgot to check or something with OBS, I haven't been back to streaming in a long time so it might even be user error. Any suggestions would help.

**Comment by malaybaku** [comment]
@phourniner Thanks for contact and sorry for late response.

VMM can stay foreground but it requires that:

- `Transparent Window` is enabled.
- `Always Foreground` is enabled, in setting window > `Window` > `Basic Settings`.
    - This option is on by default.

> when I click into the game.

Do you mean your environment runs some game app with VMM? If it is right, then 

- Some games gets get foreground than VMM, since they also prefer staying foreground.
- Disable full screen mode of the game might be a workaround.

If my answer does not follow you situation, please attach some screenshots to share the detail.

**Comment by malaybaku** [comment]
close as staled issue
